# Pinned image: hasura/graphql-engine:v2.48.16
FROM hasura/graphql-engine:v2.48.16@sha256:6ff7d8ba122c69f7be377092b0c1f5314d3e4e28274dc089cd774ce6a8ba6479

USER root

RUN apt-get update \
    && ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --only-upgrade \
        bsdutils \
        coreutils \
        curl \
        diffutils \
        gzip \
        libattr1 \
        libblkid1 \
        libc-bin \
        libc6 \
        libcap2 \
        libcurl4 \
        libexpat1 \
        libgcrypt20 \
        libgssapi-krb5-2 \
        libgnutls30 \
        libk5crypto3 \
        libkrb5-3 \
        libkrb5support0 \
        liblzma5 \
        libmount1 \
        libnghttp2-14 \
        libp11-kit0 \
        libpam-modules \
        libpam-modules-bin \
        libpam-runtime \
        libpam0g \
        libperl5.34 \
        libpq5 \
        libpython3.10-minimal \
        libpython3.10-stdlib \
        libsmartcols1 \
        libsqlite3-0 \
        libssh-4 \
        libssl3 \
        libsystemd0 \
        libudev1 \
        libuuid1 \
        mount \
        msodbcsql18 \
        openssl \
        perl \
        perl-base \
        perl-modules-5.34 \
        postgresql-client-common \
        python3.10 \
        python3.10-minimal \
        sed \
        tar \
        util-linux \
    && rm -rf /var/lib/apt/lists/* \
    && chown -R hasura:hasura /home/hasura

USER hasura

ENV HASURA_GRAPHQL_ENABLE_CONSOLE=false
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup,http-log,webhook-log,websocket-log,query-log
ENV HASURA_GRAPHQL_NO_OF_RETRIES=10
ENV HASURA_GRAPHQL_SERVER_HOST=::
ENV HASURA_GRAPHQL_SERVER_PORT=8080
ENV HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public
ENV PORT=8080

EXPOSE 8080
