# Pinned image: hasura/graphql-engine:v2.48.16
FROM hasura/graphql-engine:v2.48.16@sha256:6ff7d8ba122c69f7be377092b0c1f5314d3e4e28274dc089cd774ce6a8ba6479

USER root

RUN apt-get update \
    && ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

ENV HASURA_GRAPHQL_ENABLE_CONSOLE=false
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup,http-log,webhook-log,websocket-log,query-log
ENV HASURA_GRAPHQL_NO_OF_RETRIES=10
ENV HASURA_GRAPHQL_SERVER_HOST=::
ENV HASURA_GRAPHQL_SERVER_PORT=8080
ENV HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public
ENV PORT=8080

EXPOSE 8080
