minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "fast-uri"
  - "hono"
  - "kysely"
  - "postcss"
preferFrozenLockfile: true
engineStrict: true
strictDepBuilds: true
blockExoticSubdeps: true
packages:
  - 'apps/*'
  - 'packages/*'