[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile-indexer"
watchPatterns = ["apps/indexer/**", "railway-indexer.toml", "Dockerfile-indexer"]

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 3600
