[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile-indexer"
watchPatterns = [
  "apps/indexer/**",
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "railway-indexer.toml",
  "Dockerfile-indexer",
]

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 3600
