[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile-frontend"
watchPatterns = ["apps/frontend/**", "railway-frontend.toml", "Dockerfile-frontend"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10
